vaadin.launch-browser=true
spring.application.name=plumjob
vaadin.frontend.hotdeploy=true
vaadin.frontend.resources=frontend

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD

server.port=9090

spring.jpa.show-sql=true
spring.datasource.hikari.maximum-pool-size=1

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=plumjob.contact@gmail.com
spring.mail.password=qdvo hsxp yudt lojh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com